FROM docker/sandbox-templates:claude-code
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
USER root
#  Install libbtrfs-dev libgpgme-dev needed by podman for https://github.com/containifyci/engine-ci 
# linux-tools-common needed for perf (CPU profiling), heaptrack (Memory profiling), cargo needed for inferno (CPU and Memory profiling reporting)
# xxd tool multiple times deepseek tried to use xxd 
RUN sudo apt-get update && \
    sudo apt-get install -y wget gnupg podman xz-utils tcpdump xxd libbtrfs-dev libgpgme-dev cargo linux-tools-common heaptrack xxd && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*

RUN wget https://ziglang.org/builds/zig-aarch64-linux-0.17.0-dev.263+0add2dfc4.tar.xz && \
    tar -xf zig-aarch64-linux-0.17.0-dev.263+0add2dfc4.tar.xz -C /usr/local/bin --strip-components=1 && \
    rm zig-aarch64-linux-0.17.0-dev.263+0add2dfc4.tar.xz
# this enable memory allocatioin tracking for tests with heaptrack that is donme in the profile build step of franky
RUN sudo sed -i 's|^pub const allocator = allocator_instance.allocator();$|pub const allocator = std.heap.c_allocator;|' /usr/local/bin/lib/std/testing.zig

COPY --chown=agent:agent settings.json /home/agent/.franky/settings.json
RUN wget https://github.com/fr12k/franky/releases/latest/download/franky_${TARGETOS}_${TARGETARCH} && \
    mv franky_${TARGETOS}_${TARGETARCH} /usr/local/bin/franky

USER agent
RUN go install golang.org/x/vuln/cmd/govulncheck@latest
RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
RUN cargo install inferno
# Will install franky and settings from the Github Repository in the future.
# COPY --chown=agent:agent franky /usr/local/bin/franky
ENV ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache
ENV ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache
ENV PATH="/home/agent/.cargo/bin:${PATH}"
RUN echo 'alias claude="claude --allow-dangerously-skip-permissions --dangerously-skip-permissions"' >> ~/.bashrc && \
    echo 'alias clauder="claude --allow-dangerously-skip-permissions --dangerously-skip-permissions --resume"' >> ~/.bashrc && \
    echo 'alias franky-deepseek="./zig-out/bin/franky --profile ollama-deepseek-flash --mode proxy" >> ~/.bashrc'
